server:
  port: 8090

spring:
  application:
    name: apigateway-hiringbell-service
  cloud:
    kubernetes:
      enabled: true
    loadbalancer:
      mode: SERVICE
    discovery:
      all-namespaces: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: coreservice-service
          uri: lb://axilcorps-api-service
          predicates:
            - Path=/api/core/**
          filters:
            - AuthenticationFilter
        - id: filemanager-service
          uri: lb://filemanager-service
          predicates:
            - Path=/Files/ApplicationFiles/axilcorps/**
          filters:
            - AuthenticationFilter
        - id: authenticator-service
          uri: lb://axilcorps-auth-service
          predicates:
            - Path=/api/oauth/**
          filters:
            - AuthenticationFilter

  profiles:
    active: ${profile:prod}
  webflux:
    static-path-pattern: "/resources/**"

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 10MB
      max-request-size: 12MB

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG